# Generated by Django 5.0.1 on 2024-05-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lines',
            new_name='Contrib',
        ),
    ]
