# Generated by Django 5.0.1 on 2024-05-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='contributors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='lines',
            field=models.IntegerField(default=0),
        ),
    ]
