# Generated by Django 5.0.1 on 2024-05-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_project_last_fetch_alter_repository_last_fetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
