# Generated by Django 4.2.7 on 2024-05-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_project_skip_repository_skip_repository_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
